### ISSUE TITLE
port.h tests wrong macro for endianness

### ISSUE THREAD

**Issue by mwhudson** [cran/wk#1]
```C
#include <Rconfig.h> // for WORDS_BIG_ENDIAN

// IS_LITTLE_ENDIAN, IS_BIG_ENDIAN
#if defined(WORDS_BIG_ENDIAN)
```

Unfortunately the macro defined (or not) by Rconfig.h is `WORDS_BIGENDIAN`.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by mwhudson** [comment]
thanks, filed https://github.com/paleolimbot/wk/issues/105
